# Generated by Django 5.0.6 on 2024-05-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20240524_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.CharField(default='Warehouse', max_length=100),
        ),
    ]
